#!/bin/bash
#
\curl -L https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
rvm pkg install zlib --verify-downloads 1
rvm pkg install openssl
# As command, doesn't prompt for paging quit.
command rvm install 1.9.2 -C --with-openssl-dir=$rvm_path/usr
rvm use ruby-1.9.2
cd ~/CycleNearby
bundle install
