#!/bin/bash
#
\curl -L https://get.rvm.io | bash -s stable
~/.rvm/bin/rvm pkg install zlib --verify-downloads 1
~/.rvm/bin/rvm pkg install openssl
~/.rvm/bin/rvm install 1.9.2 --with-openssl-dir=~/.rvm/usr
source ~/.rvm/scripts/rvm
rvm use ruby-1.9.2
cd ~/CycleNearby
bundle install
